1. ~~Generators~~
2. ~~Exceptions~~
3. ~~Numpy~~
4. Pandas
5. Plotting 
6. Classes


~~sdfasdfasdf~~

**asdaasdf**

*asdfasdf*




# Generators

In [6]:
import random
students = [
    'Tzwrtzina',
    'Andreas',
    'Xristos',
    'Andromaxh',
    'Danah',
    'Antwnia',
    'Aris',
    'Maria',
    'Sofia',
    'Iwanna',
    'Aggelos',
]

def random_student():
    return random.choice(students)

rs = random_student

In [9]:
def f():
    return 5
    return 6
    return "mitsos"

In [10]:
f()

5

In [13]:
def gen():
    yield 5
    yield 6
    yield "Mitsos"

In [14]:
g = gen()

In [16]:
next(g)

5

In [17]:
next(g)

6

In [18]:
next(g)

'Mitsos'

In [19]:
next(g)

StopIteration: 

In [20]:
def gen_prime():
    
    n = 1
    while True:
        n += 1
        prime = True
        for i in range(2, n):
            if n%i == 0:
                prime = False
                break
        if prime:
            yield n
            
    

In [21]:
prime_generator = gen_prime()

In [22]:
next(prime_generator)

2

In [23]:
next(prime_generator)

3

In [24]:
next(prime_generator)

5

In [25]:
next(prime_generator)

7

In [26]:
next(prime_generator)

11

In [27]:
next(prime_generator)

13

In [28]:
for i in range(500):
    print (next(prime_generator))

17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
1009
1013
1019
1021
1031
1033
1039
1049
1051
1061
1063
1069
1087
1091
1093
1097
1103
1109
1117
1123
1129
1151
1153
1163
1171
1181
1187
1193
1201
1213
1217
1223
1229
1231
1237
1249
1259
1277
1279
1283
1289
1291
1297
1301
1303
1307
1319
1321
1327
1361
1367
1373
1381
1399
1409
1423
1427
1429
1433
1439
1447
1451
1453
1459
1471
1481
1483
1487
1489
1493
1499
1511
1523
1531
1

In [29]:
def gen():
    for i in range(1,11):
        yield i

In [34]:
g = gen()

In [35]:
next(g)

1

In [36]:
next(g)

2

In [38]:
list(g)

[3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
for i in gen():
    print (i)

1
2
3
4
5
6
7
8
9
10


In [37]:
rs()

'Sofia'

In [40]:
range(1,11)

range(1, 11)

In [41]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [42]:
d = {1:5, 2:6, 3:7}

In [44]:
list(d.keys())

[1, 2, 3]

In [45]:
l = [1,2,3,4,5,6]
def f(x):
    return x+1


In [46]:
map(f, l)

In [47]:
list(map(f,l))

[2, 3, 4, 5, 6, 7]

In [48]:
a = ['a', 'b', 'c']

In [49]:
enumerate(a)

In [50]:
list(enumerate(a))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [53]:
def g_1():
    print ('HELLO FROM GENERATOR 1')
    for i in range(1,11):
        yield i
        
        
def g_2():
    print ('HELLOG FROM GENERATOR 2')
    for i in ['a', 'b', 'c']:
        yield i

In [54]:
g_1()

<generator object g_1 at 0x107bfa750>

In [52]:
from itertools import chain

In [55]:
gen_1 = g_1()
gen_2 = g_2()

gen_3 = chain(gen_1, gen_2)

In [68]:
next(gen_3)

'c'

# Exceptions

In [77]:

a = 5
b = 0

try:
    c = a/b
except Exception:
    print ('oops')
    c = 0
    

oops


In [78]:
if b != 0:
    c = a/b
else:
    c = 0
    


In [86]:
fn = 'asdfasdfasdf'

import os

if os.path.exists(fn):
    f = open(fn)

#open(fn)


In [87]:

# Ask forgiveness not permission” 
try:
    f = open(fn)
except Exception:
    f = None
    print ('FIle not found')

FIle not found


In [88]:
adfasdf

NameError: name 'adfasdf' is not defined

In [93]:
try:
    dfgsdfgsdfg
    a=1/0
except NameError:
    print ('oops')

oops


In [94]:
try:
    a=1/0
    dfgsdfgsdfg
except NameError:
    print ('oops')

ZeroDivisionError: division by zero

In [98]:
try:
    #a=1/0
    #dfgsdfgsdfg
    open('asdfasdfasf')
except NameError:
    print ('oops den yparxei')
except ZeroDivisionError:
    print ('diaireses me to 0')
except FileNotFoundError:
    print ('Den yparxei to arxeio')
    

Den yparxei to arxeio


In [97]:
open('asdafsdf')

FileNotFoundError: [Errno 2] No such file or directory: 'asdafsdf'

In [102]:
try:
    #a=1/0
    dfgsdfgsdfg
    #open('asdfasdfasf')
except (NameError, ZeroDivisionError):
    print ('oops den yparxei, ή διαίρεση με το 0')
except FileNotFoundError:
    print ('Den yparxei to arxeio')
    
    

oops den yparxei, ή διαίρεση με το 0


In [90]:
rs()

'Sofia'

In [116]:
try:
    #a=1/0
    #dfgsdfgsdfg
    open('asdfasdfasf')
except Exception:
    print ('error')
except (NameError, ZeroDivisionError):
    print ('oops den yparxei, ή διαίρεση με το 0')
except FileNotFoundError:
    print ('Den yparxei to arxeio')
    


error


In [121]:
try:
    #a=1/0
    #dfgsdfgsdfg
    open('asdfasdfasf')
except (NameError, ZeroDivisionError):
    print ('oops den yparxei, ή διαίρεση με το 0')
except FileNotFoundError:
    print ('Den yparxei to arxeio')
except Exception:
    print ('error')
    


Den yparxei to arxeio


In [124]:
try:
    #a=1/0
    #dfgsdfgsdfg
    #open('asdfasdfasf')
    [1,2,3][5]
except (NameError, ZeroDivisionError):
    print ('oops den yparxei, ή διαίρεση με το 0')
except FileNotFoundError:
    print ('Den yparxei to arxeio')
except Exception:
    print ('error')
    


error


In [133]:
try:
    #a=1/0
    #dfgsdfgsdfg
    #open('asdfasdfasf')
    [1,2,3][5]
except Exception as e:
    print ('error')
    print (type(e))
    print (str(e))


error
<class 'IndexError'>
list index out of range


In [144]:
def f(a,b):
    '''
    a and b should be integers!!!!!
    '''
    
    if not type(a) is int  or  not type(b) is int :
        #raise Exception('parameters are not integer')
        raise TypeError('parameters are not integer')
    
    return a+b

In [ ]:
def f(a,b):
    '''
    a and b should be integers!!!!!
    '''
    
    if not type(a) is int  or  not type(b) is int :
        raise Exception('parameters are not integer')
    
    return a+b

In [139]:
f(5,3)

8

In [145]:
f(5 , 4.2)

TypeError: parameters are not integer

In [142]:
try:
    f(5 , 4.2)
except Exception as e:
    print ('Something bad happened')

Something bad happened


In [146]:
class MyFabulousException(Exception):
    '''
    This should not happen! At All!
    '''

In [148]:
raise MyFabulousException('sdsdfsdf')

MyFabulousException: sdsdfsdf

In [131]:
dir(e)

NameError: name 'e' is not defined

In [ ]:
try:

In [109]:
try :
    eval(' sum([for i in range(15)]) ')
except SyntaxError:
    print ('oops')

oops


In [151]:
try:
    #a=1/0
    a=1/2
except Exception as e:
    print ('this should not happen')
finally:
    print ('I will fix it here')

I will fix it here


In [153]:
try:
    a=1/0
    #a=1/2
except Exception as e:
    print ('this should not happen')
else:
    print ('Well Done')
finally:
    print ('I will fix it here')


this should not happen
I will fix it here


In [154]:
try:
    #a=1/0
    a=1/2
except Exception as e:
    print ('this should not happen')
else:
    print ('Well Done')
finally:
    print ('I will fix it here')


Well Done
I will fix it here


In [155]:
def f(x):
    
    if x > 10:
        raise Exception('NOOOOOOOOO')
        
    return x

In [159]:
def g(x):
    return f(x/10)

In [160]:
try:
    g(1000)
except:
    print ('G raised an exception!')

G raised an exception!


In [161]:
g(1000)

Exception: NOOOOOOOOO

In [163]:
try:
    g(1000)
except Exception as e:
    print ('G raised an exception!')
    raise e
    
    

G raised an exception!


Exception: NOOOOOOOOO

In [158]:
rs()

'Tzwrtzina'

In [106]:
3+1

4

# Numpy

In [164]:
import math

math.sqrt(20)

4.47213595499958

In [166]:
import numpy as np

In [173]:
a = [1,2,3,4,3,2]
b = [4,3,2,3,2,1]

[sum(x) for x in zip(a,b)]


[5, 5, 5, 7, 5, 3]

In [174]:
a

[1, 2, 3, 4, 3, 2]

In [175]:
a_np = np.array(a)

In [177]:
b_np = np.array(b)

In [179]:
a_np

array([1, 2, 3, 4, 3, 2])

In [180]:
b_np

array([4, 3, 2, 3, 2, 1])

In [181]:
a_np + b_np

array([5, 5, 5, 7, 5, 3])

In [183]:
a_np - b_np

array([-3, -1,  1,  1,  1,  1])

In [185]:
c = np.vstack((a_np, b_np))

In [187]:
c

array([[1, 2, 3, 4, 3, 2],
       [4, 3, 2, 3, 2, 1]])

In [188]:
c.shape

(2, 6)

In [212]:
a = np.random.random((4,3))

In [192]:
a

array([[0.91437693, 0.25769378, 0.64537131],
       [0.67786047, 0.70912712, 0.97499621],
       [0.74118468, 0.25274784, 0.42444292],
       [0.81939891, 0.71757325, 0.91173435]])

In [194]:
a[ 1 , 2 ]

0.9749962091160524

In [195]:
a[ 0:3 , 2 ]

array([0.64537131, 0.97499621, 0.42444292])

In [196]:
a[ 0:3 , 1:3 ]

array([[0.25769378, 0.64537131],
       [0.70912712, 0.97499621],
       [0.25274784, 0.42444292]])

In [197]:
a[ 0:3 , -1 ]

array([0.64537131, 0.97499621, 0.42444292])

In [198]:
a[ 0:3 ,  ]

array([[0.91437693, 0.25769378, 0.64537131],
       [0.67786047, 0.70912712, 0.97499621],
       [0.74118468, 0.25274784, 0.42444292]])

In [203]:
a[ : , 0:2]

array([[0.91437693, 0.25769378],
       [0.67786047, 0.70912712],
       [0.74118468, 0.25274784],
       [0.81939891, 0.71757325]])

In [204]:
a

array([[0.91437693, 0.25769378, 0.64537131],
       [0.67786047, 0.70912712, 0.97499621],
       [0.74118468, 0.25274784, 0.42444292],
       [0.81939891, 0.71757325, 0.91173435]])

In [205]:
type(a)

numpy.ndarray

In [206]:
a = [[1,2,3], [4,5,6]]

In [210]:
a[1][1] = { 'a':1, 'b': set([5,6,7,8])}

In [211]:
a

[[1, 2, 3], [4, {'a': 1, 'b': {5, 6, 7, 8}}, 6]]

In [209]:
a

[[1, 2, 3], [4, 5, 6]]

In [213]:
a = np.random.random((4,3))

In [214]:
a

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.56984652, 0.97092873, 0.25443137]])

In [217]:
a [ :2  ,    ]

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664]])

In [221]:
a[ [0,2]  , [1]  ]

array([0.08631511, 0.84259364])

In [222]:
a

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.56984652, 0.97092873, 0.25443137]])

In [223]:
a[ [0,2]  , [1]  ]

array([0.08631511, 0.84259364])

In [224]:
a[ [True, False, False, True]  ,    ]

array([[0.95580993, 0.08631511, 0.67902571],
       [0.56984652, 0.97092873, 0.25443137]])

In [226]:
a[ [True, False, False, True]  ,  [ False, True, True ]  ]

array([0.08631511, 0.25443137])

In [227]:
a

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.56984652, 0.97092873, 0.25443137]])

In [228]:
a [ [0,2] ,  ]

array([[0.95580993, 0.08631511, 0.67902571],
       [0.84293146, 0.84259364, 0.4136305 ]])

In [229]:
a [ [0,0,0,0,2,2,2] ,  ]

array([[0.95580993, 0.08631511, 0.67902571],
       [0.95580993, 0.08631511, 0.67902571],
       [0.95580993, 0.08631511, 0.67902571],
       [0.95580993, 0.08631511, 0.67902571],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.84293146, 0.84259364, 0.4136305 ]])

In [233]:
a [ [0,0,0,0,2,2,2] , 1:3 ]

array([[0.08631511, 0.67902571],
       [0.08631511, 0.67902571],
       [0.08631511, 0.67902571],
       [0.08631511, 0.67902571],
       [0.84259364, 0.4136305 ],
       [0.84259364, 0.4136305 ],
       [0.84259364, 0.4136305 ]])

In [234]:
a

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.56984652, 0.97092873, 0.25443137]])

In [236]:
b = [[True, False, False], [True, False, True], [False, False, False], [True, True, False]]

In [237]:
b = np.array(b)

In [238]:
a

array([[0.95580993, 0.08631511, 0.67902571],
       [0.62001427, 0.80377634, 0.67783664],
       [0.84293146, 0.84259364, 0.4136305 ],
       [0.56984652, 0.97092873, 0.25443137]])

In [239]:
b

array([[ True, False, False],
       [ True, False,  True],
       [False, False, False],
       [ True,  True, False]])

In [240]:
a[b]

array([0.95580993, 0.62001427, 0.67783664, 0.56984652, 0.97092873])

In [241]:
a[b] = 7

In [243]:
a

array([[7.        , 0.08631511, 0.67902571],
       [7.        , 0.80377634, 7.        ],
       [0.84293146, 0.84259364, 0.4136305 ],
       [7.        , 7.        , 0.25443137]])

In [244]:
a = np.random.random((4,3))

In [246]:
a

array([[0.75406692, 0.68786308, 0.9918082 ],
       [0.75447414, 0.9260037 , 0.28090686],
       [0.92425588, 0.14333805, 0.60562478],
       [0.63416726, 0.83631617, 0.65823574]])

In [247]:
b = np.ones((2,2))

In [249]:
b = 7 * b

In [250]:
b

array([[7., 7.],
       [7., 7.]])

In [251]:
a

array([[0.75406692, 0.68786308, 0.9918082 ],
       [0.75447414, 0.9260037 , 0.28090686],
       [0.92425588, 0.14333805, 0.60562478],
       [0.63416726, 0.83631617, 0.65823574]])

In [252]:
b

array([[7., 7.],
       [7., 7.]])

In [256]:
a[ 1:3 , 1:3 ] = b

In [257]:
a

array([[0.75406692, 0.68786308, 0.9918082 ],
       [0.75447414, 7.        , 7.        ],
       [0.92425588, 7.        , 7.        ],
       [0.63416726, 0.83631617, 0.65823574]])

In [258]:
a = np.random.random((4,3))

In [259]:
a

array([[0.708167  , 0.37660155, 0.7036449 ],
       [0.23996364, 0.89560585, 0.76374009],
       [0.5648255 , 0.62668968, 0.04869421],
       [0.036478  , 0.59991475, 0.2736219 ]])

In [260]:
a < 0.5

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False,  True]])

In [262]:
a[ a<0.5 ]

array([0.37660155, 0.23996364, 0.04869421, 0.036478  , 0.2736219 ])

In [263]:
a[ a<0.5 ] = 0

In [264]:
a

array([[0.708167  , 0.        , 0.7036449 ],
       [0.        , 0.89560585, 0.76374009],
       [0.5648255 , 0.62668968, 0.        ],
       [0.        , 0.59991475, 0.        ]])

In [267]:
a = np.random.random((4,3))

In [266]:
a

array([[0.43371288, 0.22946899, 0.25804008],
       [0.24412603, 0.99910025, 0.00554241],
       [0.61658454, 0.42487768, 0.70431454],
       [0.72638369, 0.52883237, 0.56692966]])

In [ ]:
a<

In [261]:
a + 10

array([[10.708167  , 10.37660155, 10.7036449 ],
       [10.23996364, 10.89560585, 10.76374009],
       [10.5648255 , 10.62668968, 10.04869421],
       [10.036478  , 10.59991475, 10.2736219 ]])

In [268]:
a = np.random.random((4,3))

In [269]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [278]:
a [  ~ (a<0.5)  ]

array([0.98027558, 0.72559567, 0.8127173 , 0.61853214, 0.84282034])

In [279]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [281]:
# 0.3 < x < 0.7

In [283]:
(a>0.3) and (a<0.7) 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [286]:
(a>0.3) & (a<0.7) 

array([[False,  True, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [287]:
a>0.3

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [288]:
a<0.7

array([[ True,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [290]:
(a>0.3) or (a<0.7) 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [293]:
(a<0.3) | (a>0.7) 

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [292]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [294]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [302]:
l = []
for x in a:
    s = sum(x)
    l.append(s)
print (l)

[1.396402472025978, 1.6412018149617655, 1.8496166822080338, 0.4565364891972742]


In [303]:
np.sum(a, axis=1)

array([1.39640247, 1.64120181, 1.84961668, 0.45653649])

In [304]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [305]:
a.T

array([[0.083404  , 0.10288884, 0.61853214, 0.15888296],
       [0.33272289, 0.72559567, 0.38826421, 0.07600264],
       [0.98027558, 0.8127173 , 0.84282034, 0.22165088]])

In [306]:
a.dot(a.T)

array([[1.07860096, 1.04669056, 1.00696864, 0.25581824],
       [1.04669056, 1.19758461, 1.03033756, 0.25163398],
       [1.00696864, 1.03033756, 1.24367722, 0.3145952 ],
       [0.25581824, 0.25163398, 0.3145952 , 0.08014931]])

In [308]:
(a.T).dot(a)

array([[0.42536814, 0.35463553, 0.72190646],
       [0.35463553, 0.79371909, 1.25994731],
       [0.72190646, 1.25994731, 2.38092487]])

In [309]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [310]:
a.reshape((2,6))

array([[0.083404  , 0.33272289, 0.98027558, 0.10288884, 0.72559567,
        0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034, 0.15888296, 0.07600264,
        0.22165088]])

In [312]:
a.reshape((6,2))

array([[0.083404  , 0.33272289],
       [0.98027558, 0.10288884],
       [0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421],
       [0.84282034, 0.15888296],
       [0.07600264, 0.22165088]])

In [313]:
a.reshape((6,3))

ValueError: cannot reshape array of size 12 into shape (6,3)

In [314]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088]])

In [316]:
a = np.vstack((a, [1,2,3]))

In [317]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088],
       [1.        , 2.        , 3.        ]])

In [323]:
a = np.hstack((a, np.array([5,6,7,8,9])  ))

ValueError: all the input arrays must have same number of dimensions

In [320]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088],
       [1.        , 2.        , 3.        ]])

In [324]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [326]:
np.hstack((a,b.T))

ValueError: all the input arrays must have same number of dimensions

In [327]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088],
       [1.        , 2.        , 3.        ]])

In [328]:
b

array([5, 6, 7, 8, 9])

In [330]:
b = np.array([[5], [6], [7], [8], [9]])

In [332]:
np.hstack((a,b))

array([[0.083404  , 0.33272289, 0.98027558, 5.        ],
       [0.10288884, 0.72559567, 0.8127173 , 6.        ],
       [0.61853214, 0.38826421, 0.84282034, 7.        ],
       [0.15888296, 0.07600264, 0.22165088, 8.        ],
       [1.        , 2.        , 3.        , 9.        ]])

In [333]:
?np.tile

In [344]:
b = np.array([5,6,7,8,9])
np.hstack((a, b.reshape((5,1))))

array([[0.083404  , 0.33272289, 0.98027558, 5.        ],
       [0.10288884, 0.72559567, 0.8127173 , 6.        ],
       [0.61853214, 0.38826421, 0.84282034, 7.        ],
       [0.15888296, 0.07600264, 0.22165088, 8.        ],
       [1.        , 2.        , 3.        , 9.        ]])

In [345]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088],
       [1.        , 2.        , 3.        ]])

In [352]:
b = np.random.random((5,3))

In [353]:
a

array([[0.083404  , 0.33272289, 0.98027558],
       [0.10288884, 0.72559567, 0.8127173 ],
       [0.61853214, 0.38826421, 0.84282034],
       [0.15888296, 0.07600264, 0.22165088],
       [1.        , 2.        , 3.        ]])

In [354]:
b

array([[0.68227114, 0.21335234, 0.24030355],
       [0.91131236, 0.23860334, 0.97262899],
       [0.16363118, 0.26472247, 0.94543148],
       [0.28880624, 0.45008973, 0.21267164],
       [0.68967187, 0.67631857, 0.07650825]])

In [355]:
a < b

array([[ True, False, False],
       [ True, False,  True],
       [False, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [337]:
b.reshape((1,-1))

array([[5, 6, 7, 8, 9]])

In [339]:
b.reshape((5,1))

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [296]:
np.max(a)

0.9802755794006675

In [297]:
np.max(a, axis=1)

array([0.98027558, 0.8127173 , 0.84282034, 0.22165088])

In [299]:
np.max(a, axis=0)

array([0.61853214, 0.72559567, 0.98027558])

In [300]:
np.sum(a, axis=1)

array([1.39640247, 1.64120181, 1.84961668, 0.45653649])

In [289]:
0.3<a<0.7

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [284]:
5+3

8

In [285]:
a + a

array([[0.166808  , 0.66544579, 1.96055116],
       [0.20577768, 1.45119134, 1.62543461],
       [1.23706427, 0.77652841, 1.68564068],
       [0.31776592, 0.15200529, 0.44330177]])

In [280]:
rs()

'Antwnia'

In [253]:
rs()

'Xristos'

# Generator Comprehensions

In [168]:
rs()

'Andromaxh'

In [ ]:
# ! pip install numpy